// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekikkxpdqmefsxxabfdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVraWtreHBkcW1lZnN4eGFiZmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTkzODEsImV4cCI6MjA1NzI5NTM4MX0.uwPOn2DLPF7it7uqzpupDmt8PlTFh-IVcqdPL2z9880";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);